Add context for client
kontent-ai/sample-app-react pull request #223
Opened 2023-04-18 12:50 UTC by IvanKiral

### Motivation

Which issue does this fix? Fixes #221 

If no issue exists, what is the fix or new feature? Were there any reasons to fix/implement things that are not obvious?

### Checklist

- [ ] Code follows coding conventions held in this repo
- [ ] Automated tests have been added
- [ ] Tests are passing
- [ ] Docs have been updated (if applicable)
- [ ] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### How to test

If manual testing is required, what are the steps?

2023-04-18 14:30 UTC, JiriLojda requested changes
Love the changes. Regarding the renaming of `projectId`s to `environmentId`s, please, replace also occurences of `project`s with `environment`s. There is quite a few of them and I stopped adding comments for each of them, I am sure you can find them. :)

2023-04-24 09:32 UTC, IvanKiral commented on src/Client.tsx
> +  globalHeaders: (_queryConfig): GlobalHeadersType[] => [
I don't understand.. what parameter?

2023-04-24 09:32 UTC, IvanKiral commented on src/Client.tsx
> +const ClientContext = createContext<ClientState>(undefined as never);
as I understand it I would need to have something of ClientState

2023-04-24 09:33 UTC, IvanKiral commented on src/Utilities/SelectedProject.ts
> +  environmentId = defaultEnvironmentId
forgot about it, deleted

2023-05-17 07:54 UTC, JiriLojda commented on src/Client.tsx
> +  globalHeaders: (_queryConfig): GlobalHeadersType[] => [
The only parameter the lambda accepts. `_queryConfig`

2023-05-17 07:56 UTC, JiriLojda commented on src/Client.tsx
> +const ClientContext = createContext<ClientState>(undefined as never);
Oh, right. Then something like `[ClientState, () => {}]`, but its not important, because you always initialize the context.

2023-05-19 05:40 UTC, merged